force-app/main/CSLogger/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Log Object to catch successes and errors</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/CSLogger/objects/Log__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Class Name attribute to this action</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <description>JSON String (for debugging API calls)</description>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Logging Level for this action</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
                <default>true</default>
                <label>ERROR</label>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message for this action</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/ObjectIDs__c.field-meta.xml
<CustomField>
    <fullName>ObjectIDs__c</fullName>
    <description>Comma delimited list of Object ID&#39;s affected by this action</description>
    <label>Object IDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object Name being saved in this action (for DML)</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack Trace (for exceptions)</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that initiated this action</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/Log_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Log_Settings</label>
    <pluralLabel>Log_Settings</pluralLabel>
</CustomObject>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Bypass_Platform_Events__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Platform_Events__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When True, LogScience will bypass platform events as configured in Log_Settings_mdt</description>
    <label>Bypass Platform Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description
    >This custom field is defaulted to NOW() and used to query the latest record from custom metadata as there is no standard created date or last modified date field in Custom metadata</description>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Enable_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Logging__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >When True, LogScience will perform its logging functions as configured in the remainder of Log_Settings__mdt</description>
    <label>Enable Logging</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Enable_Pruning__c.field-meta.xml
<CustomField>
    <fullName>Enable_Pruning__c</fullName>
    <defaultValue>false</defaultValue>
    <description
    >When True, LogScience will perform deletes on persistently-stored logging data in the Log__c object</description>
    <label>Enable Pruning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Interfaced_Class_Order__c.field-meta.xml
<CustomField>
    <fullName>Interfaced_Class_Order__c</fullName>
    <defaultValue>&quot;LogToObject,SystemDebug&quot;</defaultValue>
    <description
    >Configure Log_Settings__mdt to determine which functionality is executed when a log request is submitted to LogScience</description>
    <label>Interfaced_Class_Order</label>
    <type>TextArea</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Log_to_System_Debug__c.field-meta.xml
<CustomField>
    <fullName>Log_to_System_Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <description>All the logs should be sent to System.debug if this field is checked in</description>
    <label>Log to System Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/CSLogger/objects/Log_Settings__mdt/fields/Max_Number_Of_Logs__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_Of_Logs__c</fullName>
    <description
    >When greater than 0, the number indicated will inform the Pruning functionality how many log rows it should allow to persist</description>
    <label>Max Number Of Logs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/LogEvent__e.object-meta.xml
<CustomObject>
    <description>Platform Event to capture Logs</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/CSLogger/objects/LogEvent__e/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>Class Name attribute to this action</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <description>JSON String (for debugging API calls)</description>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Logging Level for this action</description>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message for this action</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/ObjectIDs__c.field-meta.xml
<CustomField>
    <fullName>ObjectIDs__c</fullName>
    <description>Comma delimited list of Object ID&#39;s affected by this action</description>
    <label>Object IDs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object Name being saved in this action (for DML)</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/CSLogger/objects/LogEvent__e/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Stack Trace (for exceptions)</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/CSLogger/classes/LoggerMsg.cls
/**
 * ClassName : LoggerMsg
 * Description : This is the wrapper class for the Log Object and LoggerSetting Metadata and it is used in IlogWriter
 * Interface
 */
public with sharing class LoggerMsg {
    /**
     * Wrapper class for Log Object
     */
    public class Log {
        public String className { get; set; }
        public String level { get; set; }
        public String objectName { get; set; }
        public String objectIds { get; set; }
        public String message { get; set; }
        public String stackTrace { get; set; }
        public String inJson { get; set; }
        public String user { get; set; }

        /**
         * Constructor for Log Class
         */
        public Log(
            String className,
            String level,
            String objectName,
            String objectIds,
            String message,
            String stackTrace,
            String inJSON,
            String user
        ) {
            this.className = className;
            this.level = level;
            this.objectName = objectName;
            this.objectIds = objectIds;
            this.message = message;
            this.stackTrace = stackTrace;
            this.inJson = inJson;
            this.user = user;
        }

        /**
         * Overloaded Constructor that takes LogEvent__e and parses it
         */
        public Log(LogEvent__e le) {
            this.className = le.ClassName__c;
            this.level = le.Level__c;
            this.objectName = le.ObjectName__c;
            this.objectIds = le.ObjectIDs__c;
            this.message = le.Message__c;
            this.stackTrace = le.StackTrace__c;
            this.inJson = le.JSON__c;
            this.user = le.CreatedbyId;
        }

        /**
         * Method to create the LogEvent__e instance and pass it to Logger Class
         */
        public LogEvent__e toPlatformEvent() {
            return new LogEvent__e(
                ClassName__c = this.className,
                Level__c = this.level,
                ObjectName__c = this.objectName,
                ObjectIDs__c = this.objectIds,
                Message__c = this.message,
                StackTrace__c = this.stackTrace,
                JSON__c = this.inJSON
            );
        }

        /**
         * Method to create the Log__c instance and pass it to LogToObject Class
         */
        public Log__c toLogObject() {
            return new Log__c(
                ClassName__c = this.className,
                Level__c = this.level,
                ObjectName__c = this.objectName,
                ObjectIDs__c = this.objectIds,
                Message__c = this.message,
                StackTrace__c = this.stackTrace,
                JSON__c = this.inJson,
                User__c = this.user
            );
        }
    }

    /**
     * Wrapper class for Metadata
     * Modify the constructor of this class if you wish to use something other than a Custom Metadata Type
     * to store these settings
     */
    public class LoggerSettings {
        public Boolean enableLogging;
        public Boolean enablePruning;
        public String classOrder;
        public Integer maxLogs;
        public Boolean bypassPlatformEvents;
        public Boolean logToSystemDebug;

        public LoggerSettings(Boolean platformEvent) {
            // If we are in a Unit Test, we want to fake the settings. Custom Metadata runs with SeeAllData=true
            if (Test.isRunningTest()) {
                this.enableLogging = true;
                this.enablePruning = true;
                this.classOrder = 'LogToObject';
                this.maxLogs = 10;
                this.bypassPlatformEvents = false;
                if (platformEvent) {
                    this.bypassPlatformEvents = true;
                }
                this.logToSystemDebug = false;
            } else {
                Log_Settings__mdt lsSettings = [
                    SELECT
                        Enable_Logging__c,
                        Enable_Pruning__c,
                        Interfaced_Class_Order__c,
                        Max_Number_Of_Logs__c,
                        Bypass_Platform_Events__c,
                        Log_To_System_Debug__c
                    FROM Log_Settings__mdt
                    ORDER BY Created_Date__c DESC
                    LIMIT 1
                ];
                this.enableLogging = lsSettings.Enable_Logging__c;
                this.enablePruning = lsSettings.Enable_Pruning__c;
                this.classOrder = lsSettings.Interfaced_Class_Order__c;
                this.maxLogs = Integer.valueOf(lsSettings.Max_Number_Of_Logs__c);
                this.bypassPlatformEvents = lsSettings.Bypass_Platform_Events__c;
                this.logToSystemDebug = lsSettings.Log_To_System_Debug__c;
            }
        }
    }
}