force-app/main/default/objects/ArcGIS_Map_Integration__c/ArcGIS_Map_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ArcGIS Map Integration</label>
</CustomObject>

force-app/main/default/objects/ArcGIS_Map_Integration__c/fields/ArcGIS_Type__c.field-meta.xml
<CustomField>
    <fullName>ArcGIS_Type__c</fullName>
    <label>ArcGIS Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArcGIS_Map_Integration__c/fields/Enterprise_Portal_URL__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Portal_URL__c</fullName>
    <label>Enterprise Portal URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <description>Object used to capture a user’s selection on the Clariti Map</description>
    <label>Map</label>
    <nameField>
        <displayFormat>MAP-{0000000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/Map_Geometry__c.object-meta.xml
<CustomObject>
    <description>Object used to capture the geometric details within a user’s map selection.</description>
    <label>Map Geometry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Map Geometry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Geometries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Map_Geometry__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <label>Map</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Map Geometries</relationshipLabel>
    <relationshipName>Map_Geometries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Map_Geometry__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JSON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/TestDataFactory.cls
/****************************************************************************************
Name            : TestDataFactory
Created By      : 2023-07-17 Miles Sollinger - CodeScience
Use             : Test data setup for unit tests
*****************************************************************************************/
@isTest
public with sharing class TestDataFactory {
    public static void setupOnlineApplicationSetting() {
        ArcGIS_Map_Integration__c integrationSetting = ArcGIS_Map_Integration__c.getOrgDefaults();
        integrationSetting.ArcGIS_Type__c = Constants.ARCGIS_TYPE_ONLINE;
        integrationSetting.Connection_Type__c = Constants.CONNECTION_TYPE_APPLICATION;
        integrationSetting.Client_Id__c = 'abc';
        integrationSetting.Client_Secret__c = 'def';
        integrationSetting.URL__c = 'test.arcgis.com';
        upsert integrationSetting;
    }

    public static void setupOnlineUserSetting() {
        ArcGIS_Map_Integration__c integrationSetting = ArcGIS_Map_Integration__c.getOrgDefaults();
        integrationSetting.ArcGIS_Type__c = Constants.ARCGIS_TYPE_ONLINE;
        integrationSetting.Connection_Type__c = Constants.CONNECTION_TYPE_USER;
        integrationSetting.Username__c = 'test.user';
        integrationSetting.Password__c = 'pass';
        integrationSetting.URL__c = 'test.arcgis.com';
        upsert integrationSetting;
    }

    public static void setupEnterpriseSetting() {
        ArcGIS_Map_Integration__c integrationSetting = ArcGIS_Map_Integration__c.getOrgDefaults();
        integrationSetting.ArcGIS_Type__c = Constants.ARCGIS_TYPE_ENTERPRISE;
        integrationSetting.Username__c = 'test.user';
        integrationSetting.Password__c = 'pass';
        integrationSetting.URL__c = 'test.myarcigs.com';
        integrationSetting.Enterprise_Portal_URL__c = 'test.myarcigs.com/arcgis';
        upsert integrationSetting;
    }

    public static Map__c createEmptyMap() {
        Map__c emptyMap = new Map__c();
        insert emptyMap;
        return emptyMap;
    }

    public static Map_Geometry__c createMapGeometry(Id mapId) {
        return new Map_Geometry__c(
            Map__c = mapId,
            Type__c = Constants.GEOMETRY_TYPE_JSON,
            Data__c = '{"test": "test"}'
        );
    }
}