force-app/main/default/objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <description>Object used to capture a user’s selection on the Clariti Map</description>
    <label>Map</label>
    <nameField>
        <displayFormat>MAP-{0000000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/Map_Geometry__c.object-meta.xml
<CustomObject>
    <description>Object used to capture the geometric details within a user’s map selection.</description>
    <label>Map Geometry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Map Geometry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Geometries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Map_Geometry__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <label>Map</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Map Geometries</relationshipLabel>
    <relationshipName>Map_Geometries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MapSelector.cls
public with sharing class MapSelector extends Selector {
    public MapSelector() {
        super(Schema.Map__c.SObjectType);
    }

    public MapSelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.Map__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id' };
    }

    /**
     * Gets Map and related Child Geometry records based on Map Id
     * @return Map records and related child records
     */
    public List<Map__c> getGeometryRecordsByMapId(string mapId) {
        Set<String> fields = this.getDefaultFields();
        List<String> queryFields = new List<String>(fields);
        String geoMetrySubQuery = ', (Select Data__c from Map_Geometries__r) ';

        Map<String, Object> queryArgs = new Map<String, Object>{ 'mapId' => mapId };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            geoMetrySubQuery +
            ' FROM Map__c' +
            ' WHERE ' +
            ' Id = :mapId';

        return new List<Map__c>(
            (List<Map__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }

    /**
     * Gets MapObjectId from the recordId and field Name relation
     * @return Stationary Asset Sources
     */
    public List<SObject> getMapObjectIdByRecordId(ObjectInfoMsg objectInfo) {
        List<String> queryFields = new List<String>{ 'Id', objectInfo.fieldApiName };

        Map<String, Object> queryArgs = new Map<String, Object>{ 'recordId' => objectInfo.recordId };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            ' FROM ' +
            objectInfo.objectApiName +
            ' WHERE ' +
            ' Id = :recordId';

        return new List<Sobject>(
            (List<Sobject>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}