force-app/main/default/objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <description>Object used to capture a user’s selection on the Clariti Map</description>
    <label>Map</label>
    <nameField>
        <displayFormat>MAP-{0000000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/Map_Geometry__c.object-meta.xml
<CustomObject>
    <description>Object used to capture the geometric details within a user’s map selection.</description>
    <label>Map Geometry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Map Geometry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Geometries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <label>Map</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Map Geometries</relationshipLabel>
    <relationshipName>Map_Geometries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MapGeometrySelector.cls
public with sharing class MapGeometrySelector extends Selector {
    public MapGeometrySelector() {
        super(Schema.Map_Geometry__c.SObjectType);
    }

    public MapGeometrySelector(Boolean enforceCRUD, Boolean enforceFLS, Boolean enforceShr) {
        super(Schema.Map_Geometry__c.SObjectType, enforceCRUD, enforceFLS, EnforceShr);
    }

    public override Set<String> getDefaultFields() {
        return new Set<String>{ 'Id' };
    }

    /**
     * Gets all the Geometry records based on the Map Id
     * @return Map Geometry records
     */
    public List<Map_Geometry__c> getGeometryRecordsByMapId(string mapId) {
        Set<String> fields = this.getDefaultFields();
        List<String> queryFields = new List<String>(fields);

        Map<String, Object> queryArgs = new Map<String, Object>{ 'mapId' => mapId };

        String query =
            'SELECT ' +
            String.join(queryFields, ', ') +
            ' FROM Map_Geometry__c' +
            ' WHERE ' +
            ' Map__c = :mapId';

        return new List<Map_Geometry__c>(
            (List<Map_Geometry__c>) Data.read(
                query,
                queryArgs,
                this.isEnforcingCRUD(),
                this.isEnforcingFLS(),
                this.isEnforcingShr()
            )
        );
    }
}