force-app/main/default/objects/Map__c/Map__c.object-meta.xml
<CustomObject>
    <description>Object used to capture a user’s selection on the Clariti Map</description>
    <label>Map</label>
    <nameField>
        <displayFormat>MAP-{0000000}</displayFormat>
        <label>Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/Map_Geometry__c.object-meta.xml
<CustomObject>
    <description>Object used to capture the geometric details within a user’s map selection.</description>
    <label>Map Geometry</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Map Geometry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Map Geometries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Map_Geometry__c/fields/Map__c.field-meta.xml
<CustomField>
    <fullName>Map__c</fullName>
    <label>Map</label>
    <referenceTo>Map__c</referenceTo>
    <relationshipLabel>Map Geometries</relationshipLabel>
    <relationshipName>Map_Geometries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/MapSelectorTest.cls
@IsTest
public with sharing class MapSelectorTest {
    @TestSetup
    static void makeData() {
        Map__c map1 = new Map__c();
        insert map1;

        Map_Geometry__c mapgeometry1 = new Map_Geometry__c();
        mapgeometry1.Map__c = map1.Id;

        Map_Geometry__c mapgeometry2 = new Map_Geometry__c();
        mapgeometry2.Map__c = map1.Id;

        insert new List<Map_Geometry__c>{ mapgeometry1, mapgeometry2 };
    }

    @IsTest
    public static void getGeometryRecordsByMapId_hasRecords() {
        List<Map__c> mapList = [SELECT Id FROM Map__c LIMIT 1];
        System.runAs(UserTest.createArcGISCRUDUser()) {
            System.Test.startTest();
            MapSelector mapSelector = new MapSelector();
            List<Map__c> mapRecords = mapSelector.getGeometryRecordsByMapId(mapList[0].Id);
            System.Test.stopTest();
            System.assertEquals(
                2,
                mapRecords[0].Map_Geometries__r.size(),
                'Map Geometry records are not pulled with Map Id'
            );
        }
    }

    @IsTest
    public static void getGeometryRecordsByMapId_hasNoRecords() {
        System.runAs(UserTest.createArcGISCRUDUser()) {
            System.Test.startTest();
            MapSelector mapSelector = new MapSelector();
            List<Map__c> mapRecords = mapSelector.getGeometryRecordsByMapId(null);
            System.Test.stopTest();
            System.assertEquals(0, mapRecords.size(), 'Map Geometry records are not pulled with Map Id');
        }
    }
}